default:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROJECT_ID') }}"
      schema: 'all'
      threads: 32
      keyfile: ./bq-user-json.json
      timeout_seconds: 3600
      location: US # Optional, one of US or EU
      priority: interactive
      retries: 1
    ci:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROJECT_ID') }}"
      schema: 'dbt_cloud_pr'
      threads: 32
      keyfile: ./bq-user-json.json
      timeout_seconds: 3600
      location: US # Optional, one of US or EU
      priority: interactive
      retries: 1
